// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgFMsyidQXTvKhzBP_pnKSaDmd1yH-Ruk',
    appId: '1:221094328930:android:b41aaf12d0748f4e29ef3b',
    messagingSenderId: '221094328930',
    projectId: 'my-auth-app-98f88',
    storageBucket: 'my-auth-app-98f88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwP0o0Nv2UoTdES4x8vZJ9L9y61_4AL64',
    appId: '1:221094328930:ios:d060d8ccd48f840829ef3b',
    messagingSenderId: '221094328930',
    projectId: 'my-auth-app-98f88',
    storageBucket: 'my-auth-app-98f88.appspot.com',
    androidClientId: '221094328930-lvbvjvsig2o6bs7qbokn0s4u0p16oo9d.apps.googleusercontent.com',
    iosClientId: '221094328930-n15vfga13ea7f2lmmkk5s673qk397p9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.authApp',
  );
}
